ktor:
    application:
        modules:
            - com.makassar.ApplicationKt.module
    deployment:
        port: 8080
    database:
        user: "user"
        password: "password"
        host: "db_host"
        port: "db_port"
        #maxPoolSize: 10
        db_name: makassar-management-db

