ktor:
    application:
        modules:
            - com.makassar.ApplicationKt.module
    deployment:
        port: 8080
    database:
        mongo:
            user: "mongo-makassar"
            password: "mongo-makassar-password"
            host: "localhost"
            port: "27017"
            #maxPoolSize: 10
            dbname: makassar-management-db-dev


jwt:
    secret:  "secret" # should use env variables
    issuer: "http://0.0.0.0:8080/"
    audience: "http://0.0.0.0:8080/hello"
    realm: "Access to 'hello'"
